import Foundation
import SwiftData

/// v1.0-alpha.2 — Cockpit Studio data spine.
///
/// A `Deliverable` is something MIND shipped for a Project — a SEO
/// page that went live, an audit PDF emailed to the client, an
/// invoice generated by InvoiceKit, an asset uploaded to the
/// project's CDN. One Deliverable row per artifact, so the Cockpit
/// "Livrables" surface can show a chronological feed of "what did
/// we ship for AZ Construction last month?".
///
/// Why not just reuse `Node`
/// -------------------------
/// `Node` is the legacy second-brain abstraction — it carries a
/// `kindRaw` enum, embeddings, edges, tags. A Deliverable doesn't
/// need any of that: it's a typed artifact attached to a Project,
/// not a free-form thought. A dedicated @Model:
/// - Lets the Cockpit query `project.deliverables` directly via
///   the SwiftData relationship, no `NodeKind == .deliverable`
///   predicate gymnastics.
/// - Keeps the legacy Node schema unchanged for the Wave A
///   compatibility surface (the daemon refuses to drop it anyway).
/// - Carries the commit SHA + thumbnail path inline, which would
///   otherwise pollute Node's `tags` array.
///
/// CloudKit constraints
/// --------------------
/// Same constraint set as `Project` and `Lead`: inline defaults,
/// `@Attribute(.unique)` on `id`, optional `project: Project?` with
/// nil default.
@Model
public final class Deliverable {
    @Attribute(.unique) public var id: UUID = UUID()

    /// When the deliverable was first created in MIND. Distinct
    /// from `commitMessage`'s git timestamp — a deliverable may
    /// be backfilled from an old commit days after it shipped.
    public var createdAt: Date = Date.now

    /// Raw kind discriminator. Round-trips through `DeliverableKind`
    /// via the computed accessor below. Stored as String so future
    /// kinds (`.proposal`, `.contract`) land without a schema
    /// migration.
    public var kind: String = DeliverableKind.page.rawValue

    /// Short title surfaced in the Cockpit feed. Examples:
    /// "/services/peinture-paris-15", "Audit lighthouse 2026-05".
    public var title: String = ""

    /// Optional long-form markdown body. Used by the deliverable
    /// detail view (Wave C) to host the deliverable's "story":
    /// what changed, why, what the client should look at.
    public var detail: String = ""

    /// URL or path the deliverable lives at. For `.page` this is
    /// the shipped URL (`https://www.azconstruction.fr/services/...`).
    /// For `.asset` it's a `Documents/` relative path. Optional
    /// because some deliverables (an audit PDF still under review)
    /// don't have a public URL yet.
    public var url: String?

    /// Local Documents-relative path to a PNG preview. The Cockpit
    /// feed displays this as the row's leading thumbnail; nil rows
    /// fall back to the kind-default glyph.
    public var thumbnailPath: String?

    /// Size in bytes when the deliverable is a file (asset, invoice,
    /// audit PDF). `0` for `.page` / `.audit` URL-only entries.
    public var sizeBytes: Int = 0

    /// Git commit SHA the deliverable corresponds to. Optional —
    /// only `.page` / `.asset` deliverables that landed via a
    /// commit carry one. `.invoice` / `.audit` typically don't.
    public var commitSHA: String?

    /// First line of the git commit message. Cached here so the
    /// Cockpit feed can show it without round-tripping to GitHub
    /// for every row.
    public var commitMessage: String?

    /// Owning Project. Optional + nil default for CloudKit init.
    public var project: Project?

    public init(
        id: UUID = UUID(),
        createdAt: Date = .now,
        kind: DeliverableKind = .page,
        title: String = "",
        detail: String = "",
        url: String? = nil,
        thumbnailPath: String? = nil,
        sizeBytes: Int = 0,
        commitSHA: String? = nil,
        commitMessage: String? = nil,
        project: Project? = nil
    ) {
        self.id = id
        self.createdAt = createdAt
        self.kind = kind.rawValue
        self.title = title
        self.detail = detail
        self.url = url
        self.thumbnailPath = thumbnailPath
        self.sizeBytes = sizeBytes
        self.commitSHA = commitSHA
        self.commitMessage = commitMessage
        self.project = project
    }

    // MARK: - Strongly-typed accessors

    /// Round-trips `kind` through the strongly-typed enum. Unknown
    /// values fall back to `.asset` because surfacing an unknown
    /// deliverable as a generic asset is the safest catch-all
    /// (versus `.page`, which would imply a URL existed).
    public var kindEnum: DeliverableKind {
        get { DeliverableKind(rawValue: kind) ?? .asset }
        set { kind = newValue.rawValue }
    }
}

/// v1.0-alpha.2 — What flavour of artifact this row represents.
/// `.page` is the shipped SEO page; `.screenshot` is a static
/// preview captured for the client; `.audit` is the synthesized
/// report; `.invoice` is the generated PDF; `.asset` is the
/// generic catch-all (logos, fonts, media uploads).
public enum DeliverableKind: String, CaseIterable, Sendable, Codable {
    case page
    case screenshot
    case audit
    case invoice
    case asset
}
