import Foundation

/// v0.26 — Pure `mailto:` URL builder used by the OutreachSheet's
/// "Ouvrir dans Mail" CTA. Keeping the construction in its own
/// namespace lets the test suite exercise the escaping contract
/// (subject + body + accents + recipient nil + 5000+ char bodies)
/// without ever opening UIApplication.
///
/// Construction strategy
/// ---------------------
/// `URLComponents` is the canonical way to build a `mailto:` URL on
/// Apple platforms — it handles the per-component percent-escaping
/// for us, including the gnarly cases (newlines in body, accented
/// characters in subject, commas in recipient). The alternative —
/// hand-rolled `addingPercentEncoding(withAllowedCharacters:)` —
/// would need to use `.urlQueryAllowed` MINUS `&`, `=`, `?`, `+`
/// because `mailto:` query items use the same delimiters as a web
/// URL but the `+` literal must survive to Mail.app. `URLComponents`
/// already does the right thing here, so we lean on it.
///
/// When `to` is nil, the recipient slot is omitted from the URL.
/// iOS Mail handles a recipient-less `mailto:?subject=…&body=…` by
/// opening a fresh compose window with the cursor in the To: field
/// — exactly what the user wants when they tap "Ouvrir dans Mail"
/// without an email address attached to the prospect Node.
public enum OutreachMailto {
    /// Build a `mailto:` URL ready to hand to
    /// `UIApplication.shared.open(_:)`. Returns nil only when
    /// `URLComponents` itself fails to produce a URL — empirically
    /// this never happens for any combination of subject + body we
    /// can produce in-app, but the optional return keeps the
    /// caller honest at the API boundary.
    public static func mailtoURL(
        to: String?,
        subject: String,
        body: String
    ) -> URL? {
        var components = URLComponents()
        components.scheme = "mailto"
        // `path` carries the recipient address in a `mailto:` URL —
        // not `host`. `mailto:foo@bar.com` parses as scheme=mailto,
        // path=foo@bar.com.
        if let to = to?.trimmingCharacters(in: .whitespacesAndNewlines),
           !to.isEmpty {
            components.path = to
        }
        var items: [URLQueryItem] = []
        items.append(URLQueryItem(name: "subject", value: subject))
        items.append(URLQueryItem(name: "body", value: body))
        components.queryItems = items
        // URLComponents emits `&` between query items, which iOS
        // Mail accepts. The `%` escapes inside subject + body are
        // also generated by URLComponents — we don't need to
        // pre-escape anything.
        return components.url
    }
}
