import Foundation
import GraphCore

/// v1.0-alpha.6 — Bootstrap Scaffolder.
///
/// Pure value type produced by the iOS wizard (`BootstrapWizardSheet`)
/// that captures every decision Mehdi makes when bootstrapping a fresh
/// Next.js client site. The blueprint is the single input to both
/// downstream pure surfaces:
///
///   1. `BootstrapScriptGenerator.bashScript(for:)` turns it into a
///      runnable shell script (`<slug>-scaffold.sh`) the user drops on
///      his Mac: `gh repo create` + heredoc-written template files +
///      `git push` + `vercel link`.
///   2. `BootstrapZipBuilder.archive(for:)` turns it into an in-memory
///      `[String: Data]` map mirroring the same files — convenient
///      when AirDropping a starter archive instead of running the
///      script.
///
/// Reuses `ProjectStack` + `ProjectContractType` from `GraphCore` so a
/// blueprint can be folded straight into a `Project` row at wizard
/// finish without a second mapping layer.
public struct BootstrapBlueprint: Sendable, Equatable, Codable {

    /// Stable identifier minted at wizard finish. Mirrored straight
    /// onto the parent `Project.id` so telemetry + the live cockpit
    /// row share the same UUID across surfaces.
    public let id: UUID

    /// Human-readable project name, surfaced everywhere in the
    /// scaffolded site (page title, README header, package.json
    /// `name`). Examples: `AZ Construction`, `IEF & Co`.
    public let projectName: String

    /// URL-safe slug derived from `projectName` via the same
    /// normalisation `Project.normalizeSlug(_:)` runs (lowercased,
    /// diacritics stripped, non-alphanumerics → `-`). Used inside
    /// the repo name, the local folder (`~/Developer/<slug>`), the
    /// Vercel project ID, and the scaffold zip filename.
    public let slug: String

    /// Production hostname the deployed site is reachable at, no
    /// `https://` prefix. Drives `metadataBase` in
    /// `src/app/layout.tsx`, the canonical link header, the
    /// `robots.txt`, the sitemap host, and the env variable
    /// `NEXT_PUBLIC_PLAUSIBLE_DOMAIN`.
    public let host: String

    /// GitHub organisation under which `gh repo create` mints the
    /// repo. Defaults to `MaestroMed` (Mehdi's org); the wizard
    /// surfaces the field so a one-off can target a personal account
    /// without rebuilding the app.
    public let githubOrg: String

    /// Stack family. Reuses `ProjectStack` from GraphCore so the
    /// data layer + the scaffolder agree on the same enum. The
    /// generator branches on this — only `.nextjs` writes a full
    /// Next.js template; other stacks fall back to a README-only
    /// scaffold (the rest of the stacks ship in later versions).
    public let stack: ProjectStack

    /// Hex color (`#RRGGBB`) the wizard color picker stores. Echoes
    /// straight into the scaffolded `layout.tsx` (`themeColor`) and
    /// `tailwind.config.ts` (`colors.primary`). Defaults to MIND's
    /// iris when the user keeps the default chip.
    public let primaryColor: String

    /// Whether the engagement is a one-shot build or a monthly
    /// retainer. Mirrored onto the matching `Project.contractType`
    /// so the cockpit MRR aggregation lights up immediately.
    public let contractType: ProjectContractType

    /// Recurring revenue (EUR/month) when `contractType == .retainer`.
    /// Zero for one-shot blueprints — `Project` stores both values
    /// separately so a downstream retainer add-on doesn't lose the
    /// initial one-shot price.
    public let monthlyRecurringRevenueEUR: Int

    /// Adds the `/admin` skeleton (auth.ts + bcrypt + jose, sidebar
    /// shell, dashboard, leads CRUD, settings) to the scaffold.
    /// Mirrors AZ Epoxy's backoffice pattern Mehdi already maintains.
    public let includeAdminBackoffice: Bool

    /// Adds `/content/blog/` + MDX rendering + a sample post.
    /// Mehdi uses this for SEO programmatic content on retainer
    /// engagements.
    public let includeBlogMDX: Bool

    /// Adds `next-intl` config + FR/EN messages JSON. Default on
    /// for any site Mehdi expects to serve international visitors.
    public let includeI18nFREN: Bool

    /// Adds `stripe.config.ts` + a `/api/stripe/webhook` route.
    /// Default off — most leads land via the contact form, only
    /// SaaS-y clients opt in.
    public let includeStripe: Bool

    /// Timestamp the blueprint was minted at. Used by the generator
    /// to stamp the `# Generated by MIND on <date>` header in every
    /// emitted file, and by the ZIP builder to expose a stable
    /// "generated" comment in the archive metadata.
    public let generatedAt: Date

    public init(
        id: UUID = UUID(),
        projectName: String,
        slug: String,
        host: String,
        githubOrg: String = "MaestroMed",
        stack: ProjectStack = .nextjs,
        primaryColor: String = "#5E5BD8",
        contractType: ProjectContractType = .oneshot,
        monthlyRecurringRevenueEUR: Int = 0,
        includeAdminBackoffice: Bool = false,
        includeBlogMDX: Bool = false,
        includeI18nFREN: Bool = false,
        includeStripe: Bool = false,
        generatedAt: Date = .now
    ) {
        self.id = id
        self.projectName = projectName
        self.slug = slug
        self.host = host
        self.githubOrg = githubOrg
        self.stack = stack
        self.primaryColor = primaryColor
        self.contractType = contractType
        self.monthlyRecurringRevenueEUR = monthlyRecurringRevenueEUR
        self.includeAdminBackoffice = includeAdminBackoffice
        self.includeBlogMDX = includeBlogMDX
        self.includeI18nFREN = includeI18nFREN
        self.includeStripe = includeStripe
        self.generatedAt = generatedAt
    }

    // MARK: - Derived

    /// Full GitHub repo path (`<org>/<slug>`) the `gh repo create`
    /// command uses. Surfaced separately so the iOS result sheet
    /// can hyperlink it without re-deriving the slug.
    public var githubRepoPath: String {
        "\(githubOrg)/\(slug)"
    }

    /// Canonical URL the scaffolded `metadataBase` points at.
    /// Always `https://` — the scaffolder never produces an HTTP
    /// site.
    public var canonicalURL: String {
        "https://\(host)"
    }
}
