import Foundation
import GraphCore

/// v1.0-alpha.6 — Bootstrap Scaffolder.
///
/// Pure function that converts a `BootstrapBlueprint` into an
/// idempotent, safe-to-re-run bash script (`<slug>-scaffold.sh`).
/// The script Mehdi drops on his Mac performs the same actions he
/// would otherwise click through manually:
///
/// 1. `mkdir -p ~/Developer/<slug>` + cd into it
/// 2. `gh repo create <org>/<slug> --private --clone` (soft-fail if
///    the repo already exists)
/// 3. Heredoc-write every Next.js template file via
///    `TemplateLibrary.*`
/// 4. `git add . && git commit -m "feat: bootstrap from MIND"` +
///    `git push -u origin main`
/// 5. `vercel link --project=<slug> --yes` (soft-fail — can be done
///    later)
///
/// All non-critical commands trail `|| echo "WARN: ..."` so a re-run
/// after a partial success exits cleanly. The hard prelude
/// (`set -e -u -o pipefail`) is intentionally compact — every line
/// can be commented out if Mehdi wants to debug a single step.
///
/// Determinism
/// -----------
/// The generator is pure: same blueprint → same script bytes. The
/// `generatedAt` timestamp is stamped in the header comment but
/// nothing else reads it, so the same blueprint roundtripped through
/// JSON yields identical output as long as the seed timestamps
/// agree. The tests pin a fixed-date blueprint and compare prefixes
/// rather than full body bytes, which keeps the file-content
/// templates upgradeable without breaking the regression suite.
public enum BootstrapScriptGenerator {

    /// Returns the full bash script the iOS result sheet exports
    /// via "Copier le script", "Partager le script", or the
    /// generated `.sh` file. Always starts with the shebang +
    /// strict-mode prelude.
    public static func bashScript(for blueprint: BootstrapBlueprint) -> String {
        var lines: [String] = []

        // MARK: - Header
        lines.append("#!/usr/bin/env bash")
        lines.append("set -e")
        lines.append("set -u")
        lines.append("set -o pipefail")
        lines.append("")
        lines.append("# Generated by MIND — \(formatDate(blueprint.generatedAt))")
        lines.append("# Project: \(blueprint.projectName)")
        lines.append("# Stack:   \(blueprint.stack.rawValue)")
        lines.append("# Host:    \(blueprint.host)")
        lines.append("# Repo:    \(blueprint.githubRepoPath)")
        lines.append("")

        // MARK: - Step 1: workspace
        let workspace = "$HOME/Developer/\(blueprint.slug)"
        lines.append("echo \"==> [1/8] Creating workspace at \(workspace)\"")
        lines.append("mkdir -p \"\(workspace)\"")
        lines.append("cd \"\(workspace)\"")
        lines.append("")

        // MARK: - Step 2: gh repo create + clone
        lines.append("echo \"==> [2/8] Creating GitHub repo \(blueprint.githubRepoPath)\"")
        let desc = "MIND scaffold for \(blueprint.projectName) (\(blueprint.host))"
        lines.append("gh repo create \(blueprint.githubRepoPath) --private --description \"\(desc)\" --clone 2>/dev/null || echo \"WARN: repo may already exist — continuing\"")
        // After cloning gh puts the repo under <workspace>/<slug>, cd in
        lines.append("if [ -d \"\(blueprint.slug)\" ]; then cd \"\(blueprint.slug)\"; fi")
        lines.append("")

        // MARK: - Step 3: write template files
        lines.append("echo \"==> [3/8] Writing template files\"")
        lines.append("mkdir -p src/app src/app/api/contact src/lib")
        lines.append("")
        lines.append(heredoc("package.json", contents: TemplateLibrary.packageJSON(
            slug: blueprint.slug,
            stack: blueprint.stack,
            includeAdmin: blueprint.includeAdminBackoffice,
            includeBlog: blueprint.includeBlogMDX,
            includeStripe: blueprint.includeStripe
        )))

        if blueprint.stack == .nextjs {
            lines.append(heredoc("next.config.ts", contents: TemplateLibrary.nextConfigTS()))
            lines.append(heredoc("tsconfig.json", contents: TemplateLibrary.tsconfigJSON()))
            lines.append(heredoc("tailwind.config.ts", contents: TemplateLibrary.tailwindConfigTS(primaryColor: blueprint.primaryColor)))
            lines.append(heredoc("src/app/layout.tsx", contents: TemplateLibrary.layoutTSX(
                host: blueprint.host,
                projectName: blueprint.projectName,
                primaryColor: blueprint.primaryColor
            )))
            lines.append(heredoc("src/app/page.tsx", contents: TemplateLibrary.pageTSX(projectName: blueprint.projectName)))
            lines.append(heredoc("src/app/globals.css", contents: TemplateLibrary.globalsCSS()))
            lines.append(heredoc("src/app/api/contact/route.ts", contents: TemplateLibrary.contactRouteTS()))
            lines.append(heredoc("src/app/robots.ts", contents: TemplateLibrary.robotsTS(host: blueprint.host)))
            lines.append(heredoc("src/app/sitemap.ts", contents: TemplateLibrary.sitemapTS(host: blueprint.host)))
            lines.append(heredoc("src/lib/email.ts", contents: TemplateLibrary.emailLibTS()))
            lines.append(heredoc("src/lib/rate-limit.ts", contents: TemplateLibrary.rateLimitLibTS()))
            lines.append(heredoc("vercel.json", contents: TemplateLibrary.vercelJSON()))
        }
        lines.append(heredoc(".env.example", contents: TemplateLibrary.envExample(includeStripe: blueprint.includeStripe)))
        lines.append(heredoc(".gitignore", contents: TemplateLibrary.gitignore()))
        lines.append(heredoc(".cursorrules", contents: TemplateLibrary.cursorrules(projectName: blueprint.projectName)))
        lines.append(heredoc("README.md", contents: TemplateLibrary.readme(
            projectName: blueprint.projectName,
            host: blueprint.host
        )))

        // MARK: - Step 4: optional bundles
        if blueprint.includeAdminBackoffice {
            lines.append("")
            lines.append("echo \"==> [3a/8] Scaffolding admin backoffice\"")
            lines.append("mkdir -p src/app/admin src/lib/admin")
            lines.append(heredoc("src/app/admin/page.tsx", contents: TemplateLibrary.adminPageTSX()))
            lines.append(heredoc("src/lib/admin/auth.ts", contents: TemplateLibrary.adminAuthTS()))
        }
        if blueprint.includeBlogMDX {
            lines.append("")
            lines.append("echo \"==> [3b/8] Scaffolding blog MDX\"")
            lines.append("mkdir -p content/blog")
            lines.append(heredoc("content/blog/hello-world.mdx", contents: TemplateLibrary.blogSamplePostMDX()))
        }
        if blueprint.includeI18nFREN {
            lines.append("")
            lines.append("echo \"==> [3c/8] Scaffolding i18n FR/EN\"")
            lines.append("mkdir -p messages")
            lines.append(heredoc("i18n.config.ts", contents: TemplateLibrary.nextIntlConfigTS()))
            lines.append(heredoc("messages/fr.json", contents: TemplateLibrary.i18nMessagesFR()))
            lines.append(heredoc("messages/en.json", contents: TemplateLibrary.i18nMessagesEN()))
        }
        if blueprint.includeStripe {
            lines.append("")
            lines.append("echo \"==> [3d/8] Scaffolding Stripe\"")
            lines.append("mkdir -p src/app/api/stripe/webhook")
            lines.append(heredoc("stripe.config.ts", contents: TemplateLibrary.stripeConfigTS()))
            lines.append(heredoc("src/app/api/stripe/webhook/route.ts", contents: TemplateLibrary.stripeWebhookRouteTS()))
        }

        // MARK: - Step 5: @mind/lead-webhook install line
        // (Even though it's already in package.json above, this echo
        // documents the dep so an operator scanning the script knows
        // the lead-capture wiring is in place.)
        lines.append("")
        lines.append("echo \"==> [4/8] @mind/lead-webhook wired into /api/contact/route.ts\"")
        lines.append("# npm i @mind/lead-webhook  # already in package.json")
        lines.append("")

        // MARK: - Step 6: git commit + push
        lines.append("echo \"==> [5/8] Initial commit\"")
        lines.append("git add .")
        lines.append("git commit -m \"feat: bootstrap from MIND\" || echo \"WARN: nothing to commit\"")
        lines.append("git branch -M main")
        lines.append("git push -u origin main 2>/dev/null || echo \"WARN: push failed — push manually after wiring the remote\"")
        lines.append("")

        // MARK: - Step 7: vercel link
        lines.append("echo \"==> [6/8] Linking Vercel project\"")
        lines.append("vercel link --project=\(blueprint.slug) --yes 2>/dev/null || echo \"WARN: vercel link skipped — run \\\"vercel link\\\" manually later\"")
        lines.append("")

        // MARK: - Step 8: npm install hint
        lines.append("echo \"==> [7/8] Installing dependencies\"")
        lines.append("npm install 2>/dev/null || echo \"WARN: npm install skipped — run it manually\"")
        lines.append("")

        // MARK: - Done
        lines.append("echo \"==> [8/8] Done. cd $(pwd) && npm run dev\"")
        lines.append("echo \"\"")
        lines.append("echo \"Next steps:\"")
        lines.append("echo \"  1. cp .env.example .env.local\"")
        lines.append("echo \"  2. Fill RESEND_API_KEY, MIND_PROJECT_ID, MIND_WEBHOOK_SECRET\"")
        lines.append("echo \"  3. npm run dev\"")
        lines.append("echo \"\"")
        lines.append("echo \"Vercel deployment URL will appear at https://vercel.com/\(blueprint.githubOrg.lowercased())/\(blueprint.slug)\"")

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Heredoc helper

    /// Emits a single-quoted heredoc block writing `contents` to
    /// `path`. Single-quoted EOF tags disable shell expansion so
    /// template literals like `${var}` survive untouched.
    private static func heredoc(_ path: String, contents: String) -> String {
        // Use a unique sentinel tag to avoid collisions if the
        // template ever contains a literal `EOF`.
        let tag = "MIND_BOOTSTRAP_EOF"
        return """
        mkdir -p "$(dirname \(path))"
        cat > \(path) <<'\(tag)'
        \(contents)
        \(tag)
        """
    }

    // MARK: - Date helper

    /// Stable ISO-8601 date string in UTC for the header comment.
    /// Avoids locale-specific output so the same blueprint produces
    /// the same byte stream on any machine.
    private static func formatDate(_ date: Date) -> String {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f.string(from: date)
    }
}
