#!/usr/bin/env bash
# v1.0-alpha.6 — Example bash script the Bootstrap Scaffolder produces.
# Generated for a sample blueprint:
#   projectName: AZ Construction
#   slug:        az-construction
#   host:        www.azconstruction.fr
#   stack:       nextjs
#   contract:    retainer (290€/mo)
#   modules:     admin + i18n
#
# Drop this file on the Mac, `chmod +x v1.0-alpha.6-example.sh`,
# then run it. It is idempotent — safe to re-run after a partial
# success (every non-critical step trails `|| echo "WARN: ..."`).

# NOTE: The actual file content is generated dynamically by
# BootstrapScriptGenerator.bashScript(for:) — copy the wizard's
# output via "Copier le script" on the iPhone result sheet.
# Example sketch (truncated for readability):

set -e
set -u
set -o pipefail

# Generated by MIND — 2026-05-19T00:00:00Z
# Project: AZ Construction
# Stack:   nextjs
# Host:    www.azconstruction.fr
# Repo:    MaestroMed/az-construction

echo "==> [1/8] Creating workspace at $HOME/Developer/az-construction"
mkdir -p "$HOME/Developer/az-construction"
cd "$HOME/Developer/az-construction"

echo "==> [2/8] Creating GitHub repo MaestroMed/az-construction"
gh repo create MaestroMed/az-construction --private \
  --description "MIND scaffold for AZ Construction (www.azconstruction.fr)" \
  --clone 2>/dev/null || echo "WARN: repo may already exist — continuing"
if [ -d "az-construction" ]; then cd "az-construction"; fi

echo "==> [3/8] Writing template files"
mkdir -p src/app src/app/api/contact src/lib

# ... heredoc-written: package.json, next.config.ts, tsconfig.json,
#     tailwind.config.ts, src/app/layout.tsx (with metadataBase
#     https://www.azconstruction.fr), src/app/page.tsx,
#     src/app/globals.css, src/app/api/contact/route.ts (Zod + Resend
#     + sendLeadToMIND), src/app/robots.ts, src/app/sitemap.ts,
#     src/lib/email.ts, src/lib/rate-limit.ts, vercel.json (cdg1 +
#     security headers), .env.example, .gitignore, .cursorrules,
#     README.md ...

echo "==> [3a/8] Scaffolding admin backoffice"
mkdir -p src/app/admin src/lib/admin
# heredocs: src/app/admin/page.tsx, src/lib/admin/auth.ts

echo "==> [3c/8] Scaffolding i18n FR/EN"
mkdir -p messages
# heredocs: i18n.config.ts, messages/fr.json, messages/en.json

echo "==> [4/8] @mind/lead-webhook wired into /api/contact/route.ts"

echo "==> [5/8] Initial commit"
git add .
git commit -m "feat: bootstrap from MIND" || echo "WARN: nothing to commit"
git branch -M main
git push -u origin main 2>/dev/null || echo "WARN: push failed — push manually after wiring the remote"

echo "==> [6/8] Linking Vercel project"
vercel link --project=az-construction --yes 2>/dev/null || \
  echo "WARN: vercel link skipped — run \"vercel link\" manually later"

echo "==> [7/8] Installing dependencies"
npm install 2>/dev/null || echo "WARN: npm install skipped — run it manually"

echo "==> [8/8] Done. cd $(pwd) && npm run dev"
echo ""
echo "Next steps:"
echo "  1. cp .env.example .env.local"
echo "  2. Fill RESEND_API_KEY, MIND_PROJECT_ID, MIND_WEBHOOK_SECRET"
echo "  3. npm run dev"
echo ""
echo "Vercel deployment URL will appear at https://vercel.com/maestromed/az-construction"
