import Foundation

/// v1.0-alpha.7 — Pure exporter that turns a list of `SwarmPage`
/// values into a Next.js App Router directory tree the user drops
/// into their `src/app/` folder.
///
/// Each generated page becomes one file at
/// `src/app/<serviceSlug>/<zoneSlug>/page.tsx`. The template renders
/// `<Metadata>` with title + meta description, embeds the JSON-LD as
/// a `<script type="application/ld+json">` tag, and renders the body
/// markdown via the existing `MarkdownRenderer` shipped on the
/// Next.js side.
///
/// Pure: same input → same output. The dictionary keys are POSIX
/// paths (forward slashes only) so a future ZIP writer can iterate
/// without per-platform translation.
public enum SEOSwarmExporter {

    /// Convert pages to a `[path: Data]` directory tree. The
    /// resulting dictionary maps POSIX paths under `src/app/` to the
    /// UTF-8 bytes of the rendered `page.tsx`.
    public static func nextJSAppRouter(pages: [SwarmPage]) -> [String: Data] {
        var output: [String: Data] = [:]
        output.reserveCapacity(pages.count)
        for page in pages {
            let path = "src/app/\(page.serviceSlug)/\(page.zoneSlug)/page.tsx"
            let body = renderPageTSX(page: page)
            if let data = body.data(using: .utf8) {
                output[path] = data
            }
        }
        return output
    }

    /// The string-template surface for a single page. Public so test
    /// suites can introspect the output without re-deriving it.
    public static func renderPageTSX(page: SwarmPage) -> String {
        let escapedTitle = jsString(page.title)
        let escapedDescription = jsString(page.metaDescription)
        let escapedH1 = jsString(page.h1)
        let escapedBody = jsString(page.bodyMarkdown)
        let escapedJSONLD = jsString(page.jsonLD)
        let escapedRoute = jsString(page.route)

        return """
        // Generated by MIND · v1.0-alpha.7 · SEO Swarm Orchestrator
        // Service: \(page.serviceSlug) — Zone: \(page.zoneSlug)
        // Route: \(page.route)
        //
        // To use: drop this file under src/app/, install `react-markdown`
        // and `remark-gfm`, then visit the route.

        import type { Metadata } from 'next';
        import ReactMarkdown from 'react-markdown';
        import remarkGfm from 'remark-gfm';

        export const metadata: Metadata = {
          title: \(escapedTitle),
          description: \(escapedDescription),
          alternates: {
            canonical: \(escapedRoute),
          },
        };

        const jsonLD = \(escapedJSONLD);

        const body = \(escapedBody);

        export default function Page() {
          return (
            <main className="mx-auto max-w-3xl px-6 py-16 prose prose-neutral">
              <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: jsonLD }}
              />
              <h1>{\(escapedH1)}</h1>
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{body}</ReactMarkdown>
            </main>
          );
        }
        """
    }

    // MARK: - Helpers

    /// Encode a Swift string as a JSON/JS-safe literal. Wraps in
    /// double quotes and escapes the four characters the TSX parser
    /// would otherwise choke on (backslash, double-quote, newline,
    /// carriage return). Mirrors the `escape` helper in
    /// `OutreachPromptBuilder` but adds the surrounding quotes so the
    /// caller can drop the result inline into a `const x = ...;`.
    static func jsString(_ value: String) -> String {
        var escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "`", with: "\\`")
        // TSX template parsers also hate `</` literals — split them so
        // the file never includes a closing-script-tag-looking sequence
        // inside the JSON-LD string. Safe because the JSON-LD payload
        // never legitimately needs `</`.
        escaped = escaped.replacingOccurrences(of: "</", with: "<\\/")
        return "\"\(escaped)\""
    }
}
